### ISSUE TITLE
Will the 1.17 updated be reverse compatible 

### ISSUE THREAD

**Issue by dMoonShadowElf** [emilyalexandra/trinkets#66]
i don't wanna have to delete my worlds just to add this mod but the cape feature breaks other mods

**Comment by florensie** [comment]
I'm not entirely sure what you mean by this.

If what you're asking is if you'll be able to upgrade your world to 1.17 and keep all your Trinkets:
You should definitely make a backup before you do this and place all the Trinkets you're wearing in your inventory or a chest because the slots will likely change.

**Comment by emilyalexandra** [comment]
I will attempt to read from the old trinket location and save trinkets but I do recommend backups, but I believe this person is talking about backporting trinkets 3.0.0
